### ISSUE TITLE
Flag if alignment doesn't work

### ISSUE THREAD

**Issue by philippedm** [dd7ler/iris-processing#7]
Currently, there is no way to know if the alignment did not work.  It would be useful to have a pop up or other notification that the alignment did not work and that it must be redone in order to get more accurate/reproducible results.

**Comment by Giuliariga** [comment]
We could calculate the error of the alignment for each image ( SSR  btw image n and the first image used as reference?), and define a threshold. If the error is bigger the software gives a notification. Define the proper threshold could be tricky.

**Comment by philippedm** [comment]
Is a threshold necessary?  I was thinking if SSR(image_1, image_n) < SSR(image_1, aligned_image_n), then we are in business, and if the other way around, we aren't?  

I guess that just guarantees that the alignment is better than no alignment but doesn't guarantee a quality alignment, for which a threshold would be necessary.

**Comment by Giuliariga** [comment]
Yes I was thinking what you just said, many times the alignment is reducing the error but is anyway not good enough.  
However as a start could be good to have an error message just when the alignment is completely failing or doing nothing.

**Comment by philippedm** [comment]
Corner point alignment is performed on full FOV followed by local ROI checkup with the option to reproduce the alignment on the local ROI.  Manual alignment seems to result in poor results compared to both phase correlation and corner points.  An SSR per pixel value is displayed and accepted by the user. At the moment, this issue seems to be resolved.
